/**
 * Universal Client-Side and Server-Side Data Exporter for CSG-EMS / Learnhouse.
 * 
 * Supports:
 * - Formats: CSV (RFC 4180 + UTF-8 BOM), Excel (SpreadsheetML XML .xls/.xlsx compatible), and JSON
 * - Precision formatters: Currency, Dates/Datetimes, Percentages, Nested Objects/Arrays, and Masked PII
 * - Metadata Headers: Generated by, Organization, Timestamp, Record Count, Active Filters, Data Classification, and SHA-256 Checksum
 * - Cross-environment browser download trigger with memory safety and automatic cleanup
 */

export type ExportFormat = 'csv' | 'excel' | 'json'

export type FormatterType =
  | 'text'
  | 'number'
  | 'currency'
  | 'date'
  | 'datetime'
  | 'percentage'
  | 'masked_pii'
  | 'boolean'
  | 'json'

export type PiiMaskType = 'email' | 'phone' | 'id' | 'account' | 'name' | 'auto'

export interface FormatOptions {
  currencyCode?: string
  currencySymbol?: string
  locale?: string
  dateFormat?: string
  decimals?: number
  piiType?: PiiMaskType
  booleanLabels?: { true: string; false: string }
  nullPlaceholder?: string
}

export interface ExportColumn<T = any> {
  key: string
  label: string
  type?: FormatterType
  formatOptions?: FormatOptions
  accessor?: (row: T) => any
  hidden?: boolean
  exportable?: boolean
  width?: number
}

export interface ExportMetadata {
  generatedBy?: string
  organization?: string
  timestamp?: string | Date
  recordCount?: number
  activeFilters?: Record<string, any>
  classification?: 'CONFIDENTIAL' | 'RESTRICTED' | 'INTERNAL' | 'PUBLIC'
  description?: string
  checksum?: string
}

export interface ExportOptions<T = any> {
  filename?: string
  format?: ExportFormat
  columns?: ExportColumn<T>[]
  metadata?: ExportMetadata
  includeMetadata?: boolean
  maskPii?: boolean
  selectedIds?: (string | number)[] | Set<string | number>
  idKey?: keyof T | string
}

// ---------------------------------------------------------------------------
// PII Masking Utilities
// ---------------------------------------------------------------------------

export function maskEmail(email: string): string {
  if (!email || !email.includes('@')) return email
  const [localPart, domain] = email.split('@')
  if (localPart.length <= 2) {
    return `${localPart[0] || '*'}***@${domain}`
  }
  const first = localPart[0]
  const last = localPart[localPart.length - 1]
  return `${first}***${last}@${domain}`
}

export function maskPhone(phone: string): string {
  if (!phone) return phone
  const clean = phone.replace(/[\s\-\(\)]/g, '')
  if (clean.length <= 4) return '***'
  const visible = clean.slice(-4)
  return `***-***-${visible}`
}

export function maskNationalId(id: string): string {
  if (!id) return id
  const trimmed = id.trim()
  if (trimmed.length <= 4) return '****'
  return `***-**-${trimmed.slice(-4)}`
}

export function maskBankAccount(account: string): string {
  if (!account) return account
  const trimmed = account.trim()
  if (trimmed.length <= 4) return '****'
  return `****${trimmed.slice(-4)}`
}

export function maskName(name: string): string {
  if (!name) return name
  const parts = name.trim().split(/\s+/)
  return parts
    .map((p) => {
      if (p.length <= 1) return p
      return `${p[0]}${'*'.repeat(Math.min(p.length - 1, 4))}`
    })
    .join(' ')
}

export function maskPiiValue(value: any, maskType: PiiMaskType = 'auto'): string {
  if (value === null || value === undefined) return ''
  const str = String(value).trim()
  if (!str) return ''

  if (maskType === 'email' || (maskType === 'auto' && str.includes('@') && str.includes('.'))) {
    return maskEmail(str)
  }
  if (maskType === 'phone' || (maskType === 'auto' && /^(\+?[0-9\s\-()]{7,20})$/.test(str))) {
    return maskPhone(str)
  }
  if (maskType === 'account') {
    return maskBankAccount(str)
  }
  if (maskType === 'id') {
    return maskNationalId(str)
  }
  if (maskType === 'name') {
    return maskName(str)
  }

  // Fallback auto mask for general sensitive strings
  if (str.length <= 3) return '***'
  return `${str.slice(0, 1)}***${str.slice(-1)}`
}

// ---------------------------------------------------------------------------
// Precision Value Formatters
// ---------------------------------------------------------------------------

export function formatExportCurrency(
  value: any,
  options?: { currencyCode?: string; currencySymbol?: string; locale?: string; decimals?: number }
): string {
  if (value === null || value === undefined || value === '') return '—'
  const num = typeof value === 'number' ? value : parseFloat(String(value).replace(/[^0-9.-]+/g, ''))
  if (isNaN(num)) return String(value)

  const symbol = options?.currencySymbol || 'Rs. '
  const decimals = options?.decimals ?? 2
  const formattedNum = num.toLocaleString(options?.locale || 'en-US', {
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  })
  return `${symbol}${formattedNum}`
}

export function formatExportDate(
  value: any,
  options?: { includeTime?: boolean; locale?: string }
): string {
  if (!value) return '—'
  try {
    const d = value instanceof Date ? value : new Date(value)
    if (isNaN(d.getTime())) return String(value)
    if (options?.includeTime) {
      return d.toISOString().replace('T', ' ').substring(0, 19)
    }
    return d.toISOString().slice(0, 10)
  } catch {
    return String(value)
  }
}

export function formatExportPercentage(
  value: any,
  options?: { decimals?: number }
): string {
  if (value === null || value === undefined || value === '') return '—'
  const num = typeof value === 'number' ? value : parseFloat(String(value))
  if (isNaN(num)) return String(value)
  const decimals = options?.decimals ?? 1
  return `${num.toFixed(decimals)}%`
}

export function formatExportValue<T = any>(
  raw: any,
  col: ExportColumn<T>,
  row: T,
  maskPii: boolean = false
): string {
  if (raw === null || raw === undefined) {
    return col.formatOptions?.nullPlaceholder ?? ''
  }

  if (maskPii && (col.type === 'masked_pii' || col.formatOptions?.piiType)) {
    return maskPiiValue(raw, col.formatOptions?.piiType ?? 'auto')
  }

  switch (col.type) {
    case 'currency':
      return formatExportCurrency(raw, col.formatOptions)
    case 'date':
      return formatExportDate(raw, { includeTime: false, locale: col.formatOptions?.locale })
    case 'datetime':
      return formatExportDate(raw, { includeTime: true, locale: col.formatOptions?.locale })
    case 'percentage':
      return formatExportPercentage(raw, col.formatOptions)
    case 'masked_pii':
      return maskPiiValue(raw, col.formatOptions?.piiType ?? 'auto')
    case 'boolean': {
      const labels = col.formatOptions?.booleanLabels ?? { true: 'Yes', false: 'No' }
      return raw ? labels.true : labels.false
    }
    case 'number': {
      const num = typeof raw === 'number' ? raw : parseFloat(raw)
      if (isNaN(num)) return String(raw)
      const decimals = col.formatOptions?.decimals
      return decimals !== undefined ? num.toFixed(decimals) : String(num)
    }
    case 'json':
      try {
        return typeof raw === 'object' ? JSON.stringify(raw) : String(raw)
      } catch {
        return String(raw)
      }
    default:
      if (typeof raw === 'object') {
        if (Array.isArray(raw)) {
          return raw.map((item) => (typeof item === 'object' ? JSON.stringify(item) : String(item))).join('; ')
        }
        return JSON.stringify(raw)
      }
      return String(raw)
  }
}

// ---------------------------------------------------------------------------
// Checksum Generator (SHA-256 for integrity auditing)
// ---------------------------------------------------------------------------

export async function computeDataChecksum(content: string): Promise<string> {
  if (typeof crypto !== 'undefined' && crypto.subtle && typeof TextEncoder !== 'undefined') {
    try {
      const msgBuffer = new TextEncoder().encode(content)
      const hashBuffer = await crypto.subtle.digest('SHA-256', msgBuffer)
      const hashArray = Array.from(new Uint8Array(hashBuffer))
      return hashArray.map((b) => b.toString(16).padStart(2, '0')).join('')
    } catch {
      // Fallback
    }
  }
  // Simple fast deterministic hash fallback
  let hash = 0
  for (let i = 0; i < content.length; i++) {
    const char = content.charCodeAt(i)
    hash = (hash << 5) - hash + char
    hash |= 0
  }
  return `crc-${Math.abs(hash).toString(16)}`
}

// ---------------------------------------------------------------------------
// CSV Generator
// ---------------------------------------------------------------------------

function escapeCsvCell(value: string): string {
  if (value.includes('"') || value.includes(',') || value.includes('\n') || value.includes('\r')) {
    return `"${value.replace(/"/g, '""')}"`
  }
  return value
}

export function generateCsvContent<T = any>(
  data: T[],
  columns: ExportColumn<T>[],
  options?: ExportOptions<T>
): string {
  const activeColumns = columns.filter((c) => !c.hidden && c.exportable !== false)
  const lines: string[] = []

  // UTF-8 BOM for Microsoft Excel auto-detection
  const BOM = '\uFEFF'

  // Metadata Header Block
  if (options?.includeMetadata !== false && options?.metadata) {
    const meta = options.metadata
    lines.push(`# ============================================================`)
    lines.push(`# CSG-EMS UNIVERSAL DATA EXPORT`)
    if (meta.organization) lines.push(`# Organization: ${meta.organization}`)
    if (meta.generatedBy) lines.push(`# Generated By: ${meta.generatedBy}`)
    lines.push(`# Timestamp: ${meta.timestamp ? (meta.timestamp instanceof Date ? meta.timestamp.toISOString() : meta.timestamp) : new Date().toISOString()}`)
    lines.push(`# Record Count: ${data.length}`)
    if (meta.classification) lines.push(`# Classification: ${meta.classification}`)
    if (meta.activeFilters && Object.keys(meta.activeFilters).length > 0) {
      lines.push(`# Active Filters: ${JSON.stringify(meta.activeFilters)}`)
    }
    if (meta.checksum) lines.push(`# Checksum: ${meta.checksum}`)
    lines.push(`# ============================================================`)
    lines.push(``)
  }

  // Header row
  const headerRow = activeColumns.map((col) => escapeCsvCell(col.label)).join(',')
  lines.push(headerRow)

  // Data rows
  for (const row of data) {
    const rowValues = activeColumns.map((col) => {
      let rawVal: any
      if (col.accessor) {
        rawVal = col.accessor(row)
      } else if (col.key in (row as any)) {
        rawVal = (row as any)[col.key]
      } else {
        // Deep nested key resolution (e.g. 'user.profile.name')
        rawVal = col.key.split('.').reduce((acc, part) => acc && acc[part], row as any)
      }
      const formatted = formatExportValue(rawVal, col, row, options?.maskPii)
      return escapeCsvCell(formatted)
    })
    lines.push(rowValues.join(','))
  }

  return BOM + lines.join('\r\n')
}

// ---------------------------------------------------------------------------
// Excel XML (SpreadsheetML 2003 XML) Generator
// Native Excel XML compatible with Excel 2003-2024, LibreOffice, and Google Sheets
// ---------------------------------------------------------------------------

function escapeXml(unsafe: string): string {
  return unsafe
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

export function generateExcelXmlContent<T = any>(
  data: T[],
  columns: ExportColumn<T>[],
  options?: ExportOptions<T>
): string {
  const activeColumns = columns.filter((c) => !c.hidden && c.exportable !== false)
  const meta = options?.metadata
  const nowStr = meta?.timestamp
    ? meta.timestamp instanceof Date
      ? meta.timestamp.toISOString()
      : meta.timestamp
    : new Date().toISOString()

  let xml = `<?xml version="1.0" encoding="UTF-8"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:html="http://www.w3.org/TR/REC-html40">
 <DocumentProperties xmlns="urn:schemas-microsoft-com:office:office">
  <Title>${escapeXml(options?.filename || 'Data Export')}</Title>
  <Author>${escapeXml(meta?.generatedBy || 'CSG-EMS Exporter')}</Author>
  <Created>${nowStr}</Created>
  <Company>${escapeXml(meta?.organization || 'CSG Education')}</Company>
 </DocumentProperties>
 <Styles>
  <Style ss:ID="Default" ss:Name="Normal">
   <Alignment ss:Vertical="Center"/>
   <Borders/>
   <Font ss:FontName="Calibri" x:Family="Swiss" ss:Size="11" ss:Color="#1F2937"/>
   <Interior/>
   <NumberFormat/>
   <Protection/>
  </Style>
  <Style ss:ID="MetaLabel">
   <Font ss:FontName="Calibri" x:Family="Swiss" ss:Size="10" ss:Color="#4B5563" ss:Bold="1"/>
   <Interior ss:Color="#F3F4F6" ss:Pattern="Solid"/>
  </Style>
  <Style ss:ID="MetaVal">
   <Font ss:FontName="Calibri" x:Family="Swiss" ss:Size="10" ss:Color="#1F2937"/>
   <Interior ss:Color="#F9FAFB" ss:Pattern="Solid"/>
  </Style>
  <Style ss:ID="HeaderStyle">
   <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="2" ss:Color="#D1D5DB"/>
   </Borders>
   <Font ss:FontName="Calibri" x:Family="Swiss" ss:Size="11" ss:Color="#FFFFFF" ss:Bold="1"/>
   <Interior ss:Color="#1E293B" ss:Pattern="Solid"/>
  </Style>
  <Style ss:ID="DataCell">
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#E5E7EB"/>
    <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#E5E7EB"/>
   </Borders>
   <Font ss:FontName="Calibri" x:Family="Swiss" ss:Size="10"/>
  </Style>
  <Style ss:ID="NumberCell">
   <Alignment ss:Horizontal="Right" ss:Vertical="Center"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#E5E7EB"/>
   </Borders>
   <Font ss:FontName="Calibri" x:Family="Swiss" ss:Size="10"/>
   <NumberFormat ss:Format="#,##0.00"/>
  </Style>
 </Styles>
 <Worksheet ss:Name="Export">
  <Table ss:DefaultRowHeight="20">`

  // Column definitions
  for (const col of activeColumns) {
    const width = col.width || 120
    xml += `\n   <Column ss:Width="${width}"/>`
  }

  // Optional Metadata Rows
  if (options?.includeMetadata !== false && meta) {
    xml += `
   <Row ss:Height="22">
    <Cell ss:StyleID="MetaLabel"><Data ss:Type="String">CSG-EMS Universal Data Export</Data></Cell>
    <Cell ss:StyleID="MetaVal"><Data ss:Type="String">${escapeXml(options?.filename || 'Export')}</Data></Cell>
   </Row>
   <Row ss:Height="18">
    <Cell ss:StyleID="MetaLabel"><Data ss:Type="String">Organization:</Data></Cell>
    <Cell ss:StyleID="MetaVal"><Data ss:Type="String">${escapeXml(meta.organization || 'N/A')}</Data></Cell>
    <Cell ss:StyleID="MetaLabel"><Data ss:Type="String">Generated By:</Data></Cell>
    <Cell ss:StyleID="MetaVal"><Data ss:Type="String">${escapeXml(meta.generatedBy || 'System')}</Data></Cell>
   </Row>
   <Row ss:Height="18">
    <Cell ss:StyleID="MetaLabel"><Data ss:Type="String">Export Date:</Data></Cell>
    <Cell ss:StyleID="MetaVal"><Data ss:Type="String">${escapeXml(nowStr)}</Data></Cell>
    <Cell ss:StyleID="MetaLabel"><Data ss:Type="String">Total Records:</Data></Cell>
    <Cell ss:StyleID="MetaVal"><Data ss:Type="Number">${data.length}</Data></Cell>
   </Row>
   <Row ss:Height="10"><Cell ss:StyleID="Default"/></Row>`
  }

  // Header Row
  xml += `\n   <Row ss:Height="26">`
  for (const col of activeColumns) {
    xml += `\n    <Cell ss:StyleID="HeaderStyle"><Data ss:Type="String">${escapeXml(col.label)}</Data></Cell>`
  }
  xml += `\n   </Row>`

  // Data Rows
  for (const row of data) {
    xml += `\n   <Row ss:Height="20">`
    for (const col of activeColumns) {
      let rawVal: any
      if (col.accessor) {
        rawVal = col.accessor(row)
      } else if (col.key in (row as any)) {
        rawVal = (row as any)[col.key]
      } else {
        rawVal = col.key.split('.').reduce((acc, part) => acc && acc[part], row as any)
      }
      const formatted = formatExportValue(rawVal, col, row, options?.maskPii)
      const isNum = (col.type === 'number' || col.type === 'currency') && !isNaN(Number(rawVal)) && rawVal !== '' && rawVal !== null

      if (isNum && !options?.maskPii) {
        xml += `\n    <Cell ss:StyleID="NumberCell"><Data ss:Type="Number">${Number(rawVal)}</Data></Cell>`
      } else {
        xml += `\n    <Cell ss:StyleID="DataCell"><Data ss:Type="String">${escapeXml(formatted)}</Data></Cell>`
      }
    }
    xml += `\n   </Row>`
  }

  xml += `
  </Table>
  <WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel">
   <Selected/>
   <FreezePanes/>
   <FrozenNoSplit/>
   <SplitHorizontal>${options?.includeMetadata !== false && meta ? 5 : 1}</SplitHorizontal>
   <TopRowBottomPane>${options?.includeMetadata !== false && meta ? 5 : 1}</TopRowBottomPane>
   <ActivePane>2</ActivePane>
  </WorksheetOptions>
 </Worksheet>
</Workbook>`

  return xml
}

// ---------------------------------------------------------------------------
// JSON Generator
// ---------------------------------------------------------------------------

export function generateJsonContent<T = any>(
  data: T[],
  columns: ExportColumn<T>[],
  options?: ExportOptions<T>
): string {
  const activeColumns = columns.filter((c) => !c.hidden && c.exportable !== false)
  const transformedRows = data.map((row) => {
    const item: Record<string, any> = {}
    for (const col of activeColumns) {
      let rawVal: any
      if (col.accessor) {
        rawVal = col.accessor(row)
      } else if (col.key in (row as any)) {
        rawVal = (row as any)[col.key]
      } else {
        rawVal = col.key.split('.').reduce((acc, part) => acc && acc[part], row as any)
      }
      item[col.key] = formatExportValue(rawVal, col, row, options?.maskPii)
    }
    return item
  })

  const payload = {
    metadata: {
      exportedAt: options?.metadata?.timestamp
        ? options.metadata.timestamp instanceof Date
          ? options.metadata.timestamp.toISOString()
          : options.metadata.timestamp
        : new Date().toISOString(),
      recordCount: transformedRows.length,
      organization: options?.metadata?.organization || 'CSG Education',
      generatedBy: options?.metadata?.generatedBy || 'User',
      classification: options?.metadata?.classification || 'CONFIDENTIAL',
      activeFilters: options?.metadata?.activeFilters || {},
      checksum: options?.metadata?.checksum,
    },
    columns: activeColumns.map((c) => ({ key: c.key, label: c.label, type: c.type || 'text' })),
    data: transformedRows,
  }

  return JSON.stringify(payload, null, 2)
}

// ---------------------------------------------------------------------------
// Browser File Download Trigger
// ---------------------------------------------------------------------------

export function triggerBrowserDownload(
  content: string | Blob,
  filename: string,
  mimeType: string
): void {
  if (typeof window === 'undefined') return

  const blob = content instanceof Blob ? content : new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.setAttribute('download', filename)
  document.body.appendChild(link)
  link.click()

  // Clean up memory
  setTimeout(() => {
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }, 200)
}

// ---------------------------------------------------------------------------
// Universal Export Master Function
// ---------------------------------------------------------------------------

export async function executeDataExport<T = any>(
  data: T[],
  columns: ExportColumn<T>[],
  options: ExportOptions<T> = {}
): Promise<{ success: boolean; recordCount: number; filename: string; format: ExportFormat }> {
  const format = options.format || 'csv'
  const rawPrefix = options.filename || 'export'
  const cleanPrefix = rawPrefix.replace(/[^a-zA-Z0-9_-]/g, '_').toLowerCase()
  const dateSuffix = new Date().toISOString().slice(0, 10)

  // Filter selected rows if requested
  let targetData = data
  if (options.selectedIds && (options.selectedIds as any).size !== undefined) {
    const idSet = options.selectedIds as Set<string | number>
    if (idSet.size > 0) {
      const idKey = options.idKey || ('id' in (data[0] || {}) ? 'id' : 'user_id')
      targetData = data.filter((row: any) => idSet.has(row[idKey]))
    }
  } else if (Array.isArray(options.selectedIds) && options.selectedIds.length > 0) {
    const idSet = new Set(options.selectedIds)
    const idKey = options.idKey || ('id' in (data[0] || {}) ? 'id' : 'user_id')
    targetData = data.filter((row: any) => idSet.has(row[idKey]))
  }

  let finalContent: string
  let fullFilename: string
  let mimeType: string

  const metadata: ExportMetadata = {
    ...options.metadata,
    recordCount: targetData.length,
    timestamp: options.metadata?.timestamp || new Date(),
  }

  if (format === 'csv') {
    fullFilename = `${cleanPrefix}_${dateSuffix}.csv`
    mimeType = 'text/csv;charset=utf-8;'
    finalContent = generateCsvContent(targetData, columns, { ...options, metadata })
    metadata.checksum = await computeDataChecksum(finalContent)
  } else if (format === 'excel') {
    fullFilename = `${cleanPrefix}_${dateSuffix}.xls`
    mimeType = 'application/vnd.ms-excel;charset=utf-8;'
    finalContent = generateExcelXmlContent(targetData, columns, { ...options, metadata })
  } else {
    fullFilename = `${cleanPrefix}_${dateSuffix}.json`
    mimeType = 'application/json;charset=utf-8;'
    finalContent = generateJsonContent(targetData, columns, { ...options, metadata })
  }

  triggerBrowserDownload(finalContent, fullFilename, mimeType)

  return {
    success: true,
    recordCount: targetData.length,
    filename: fullFilename,
    format,
  }
}
